stages:
  - build
  - test
  - sonarqube
  - deploy

variables:
  SONARQUBE_IMAGE: sonarqube:latest
  DATABASE_IMAGE: mcr.microsoft.com/mssql/server:latest
  BACKEND_IMAGE: grooveshare-be:latest
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - docker info

sonarqube_analysis:
  stage: sonarqube
  script:
    - ./gradlew jacocoTestReport sonarqube
  only:
    - main


build:
  stage: build
  script:
    - ./gradlew clean assemble
    - docker build -t $BACKEND_IMAGE .

test:
  stage: test
  script:
    - ./gradlew test

deploy_backend:
  stage: deploy
  script:
    - docker stop grooveshare-be || $true
    - docker rm grooveshare-be || $true
    - docker run -d -p 8090:8080 --net=docker_demo_network_staging --env spring_profiles_active=staging --name grooveshare-be $BACKEND_IMAGE

deploy_database:
  stage: deploy
  script:
    - docker stop groovesharedb || $true
    - docker rm groovesharedb || $true
    - docker pull $DATABASE_IMAGE
    - docker run -d -e ACCEPT_EULA=Y -e SA_PASSWORD=booMPentakill27 -p 1433:1433 --name groovesharedb $DATABASE_IMAGE