concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "GrooveShare runner"
  url = "https://git.fhict.nl/"
  id = 8776
  token = "4xrJtoByxSnZtVis_S8c"
  token_obtained_at = 2023-09-21T16:42:51Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.cache]
    MaxUploadedArchiveSize = 0
